name: Linters

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  lint_pylint:
    if: (github.event_name == 'pull_request' && github.event.pull_request.user.login == 'dependabot[bot]') || github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9 and pip
      run: |
        sudo add-apt-repository ppa:deadsnakes/ppa -y
        sudo apt update
        sudo apt install -y python3.9 python3.9-distutils
        curl -s https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        sudo python3.9 get-pip.py

    - name: Install pylint
      run: |
        pip install pylint

    - name: Run pylint
      run: |
        pylint --disable=all -e W0311 -e C0303 --jobs=0 --indent-string='    ' **/*.py
