name: RPM Build and Upload

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create tag based on date
        id: create_tag
        run: echo ::set-env name=TAG::$(date +'%Y%m%d%H%M').0.0
        shell: bash

      - name: Set Version
        run: echo "VERSION=${{ env.TAG }}" >> $GITHUB_ENV

      - name: Run Docker Container
        run: docker run --privileged -d --name builder --network host rockylinux:9 /bin/sleep infinity

      - name: Install build tools RPM
        run: |
          docker cp ./ builder:/build
          docker exec builder bash -c "yum install -y epel-release && yum install -y make git mock"
          docker exec builder bash -c "rm -rf /etc/mock/default.cfg"

      - name: Setup SDK
        run: |
          docker exec builder bash -c "curl https://raw.githubusercontent.com/redBorder/repoinit/master/sdk9.cfg > /build/sdk9.cfg"
          docker exec builder bash -c "echo \"config_opts['use_host_resolv'] = True\" >> /build/sdk9.cfg"
          docker exec builder bash -c "ln -s /build/sdk9.cfg /etc/mock/default.cfg"

      - name: Build RPM using mock
        run: |
          docker exec builder bash -c "git config --global --add safe.directory /build"
          docker exec builder bash -c "cd /build/ && VERSION=${{ env.TAG }} make rpm"

      - name: Copy RPMS
        run: |
          docker cp builder:/build/packaging/rpm/pkgs/. ./rpms

      - name: Delete non-.rpm files
        run: |
          find ./rpms -type f -not -name '*.rpm' -exec rm {} \;

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./rpms/*
          tag_name: ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
